### PR TITLE
Migrate to GitHub packages

### PR DESCRIPTION
**Pull request by alvinsj**

### CODE REVIEW

**Review by jarjan — APPROVED** [review]
Update yarn.lock file too?

**Comment by alvinsj** [comment]
my god, thanks for reminding. 
noticed it doesn't use our private packages, but didn't expect it is still fetching from nexus.

**Comment by jarjan** [comment]
@alvinsj that's why we have reviews :)
But anyway, on the nexus deletion day we will have some apps broken, I think :)

**Comment by alvinsj** [comment]
just checked, don't need to republish - not used in package installation https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-check-into-source-control

**Comment by alvinsj** [comment]
>  But anyway, on the nexus deletion day we will have some apps broken, I think :)

yes, that's why I made an apps section too in the migration docs. I think it makes sense to do it only after all these packages are migrated. I will let mario know.

**Pull request merged**
